### PR TITLE
An awful lot of new stuff

### PR DESCRIPTION
**Pull request by zijistark**
- Working draft of PlusFaction integration and dynamic civil war overhaul
- SWMH: All-new events for the de jure expansion of Christian Iberia kingdoms
- When the ERE regains Rum's de jure territory, it will now be automatically shifted back under the ERE (under Anatolia/Iconium/Konya)
- Misc.

### CODE REVIEW

**Comment by escalonn** [comment]
What if Rum has drifted additional non-ERE territory into itself? Controlling *that* becomes necessary for the instant drift of it all back to ERE? Or, those extra parts remain de jure Rum, while the original parts go back to Ikonion?

**Comment by zijistark** [comment]
Controlling all of whatever `k_rum` becomes will be necessary to convert `k_rum` back to an ERE title.

**Comment by zijistark** [comment]
At least, in terms of instant assimilation.

**Comment by escalonn** [comment]
And if the Sultan of Rum loses his de jure land but still holds land de facto – he keeps his kingdom but it becomes titular?

**Comment by zijistark** [comment]
Correct.

**Pull request merged**
