### PR TITLE
Test candidate for revised civil war system

### PR DESCRIPTION
**Pull request by zijistark**

### CODE REVIEW

**Comment by escalonn** [comment]
all those "0" diffs at the bottom of the files changed list look suspicious. WAD?

**Comment by escalonn** [comment]
EMF has both e_null and e_hip now?

**Comment by zijistark** [comment]
the "No changes." files have _definitely_ been changed, so yeah, it looks extremely suspicious. However, I've never even seen such a thing before... If they had "No changes," then why is it in the Files Changed diff? All those files were changed heavily.

**Comment by zijistark** [comment]
> EMF has both e_null and e_hip now?

Yes, EMF directly integrates HIP_Common now.  Once I separate the EMF-used event pictures from not and get some spare moments, the event pictures used by VIET Events in HIP_Common will also be re-integrated into VEvents (at least 95% of them are VIET-only), and then I will delete the HIP repository and remove HIP_Common from the installer.

Having the packages be separate causes a lot of extra complexity for zero gain: no other HIP module actually uses Isis, and no other HIP module ever will, so that experiment failed, and Isis and such will be strictly an EMF thing from here forward.

**Pull request merged**
