### PR TITLE
Add custom obligation law graphics

### PR DESCRIPTION
**Pull request by thefinestsieve**
This should be everything ready to go, unless I've misinterpreted the new graphics setup somehow, which is always possible.

### CODE REVIEW

**Comment by zijistark** [comment]
I'm going to wait to merge this until either I can get time to figure out what I need to do our modded domestic_laws.gui (@Rylock modded it for me so that obligations laws would display as text for the initial release, and since it worked, I haven't looked into the actual implementation) to retain the 5 levels of obligations (instead of 9) as well as their spacing to better fill the laws tab horizontally due to their lower number than the vanilla laws for which the GUI was intended OR @thefinestsieve just does it for me.  Either way, I imagine that it should be pretty dang simple, but I'm not as hot w/ GUI modding as @thefinestsieve, so he may want to take a crack at it if he's interested, as I'm guessing he could also make it even better (and with less effort).

**Comment by thefinestsieve** [comment]
I'll take a look at it when I get a spare moment

**Comment by thefinestsieve** [comment]
This now works properly. The obligations are spaced out just like the other sliders and work just fine in my testing. (Yes, I actually booted up the game.)

**Comment by zijistark** [comment]
Awesome.

**Pull request merged**
