### PR TITLE
(SWMH) Added cultural retinue subunit type for Geats (gothic)

### PR DESCRIPTION
**Pull request by zijistark**

### CODE REVIEW

**Comment by escalonn** [comment]
Nothing for `east_gothic`?

**Comment by zijistark** [comment]
I don't approve of Crimean Goths, no. [Wasn't this just added?]

**Comment by escalonn** [comment]
nah, they've been around since EE

**Comment by zijistark** [comment]
Cataphracts. Already in. `culture_group` magic.

**Pull request merged**
